# Generated by Django 4.2.3 on 2023-07-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_actualizado_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(default='Pais predeterminado', max_length=100),
        ),
    ]
